# Generated by Django 3.2.3 on 2021-05-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_auto_20210517_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
    ]
